version: "3.8"
services: 
  md_updater:
    build:
      context: .
      dockerfile: dockerfile
    container_name: md_updater
    image: md_updater
    environment:
      - IS_DOCKER=true
      - TIMEOUT=4
      - USE_WGET=true
    volumes: 
      - ./data:/md_updater/data
      - ./login.json:/md_updater/login.json
      - ./log.txt:/md_updater/log.txt
      - ./blacklisted.txt:/md_updater/blacklisted.txt
