version: "3.8"
services: 
  md_updater:
    container_name: md_updater
    image: md_updater
    environment:
      - IS_DOCKER=true
      - TIMEOUT=4
    volumes: 
      - ./data:/md_updater/data
      - ./login.json:/md_updater/login.json
